# Generated by Django 4.1.7 on 2023-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0002_remove_order_table_ordersnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
