# Generated by Django 4.1.7 on 2023-10-23 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0006_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersnumber',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
