# Generated by Django 4.2.11 on 2024-04-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0007_ordersnumber_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='order_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
