# Generated by Django 5.0.4 on 2024-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0009_domainapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='wallet_address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
