# Generated by Django 5.0.4 on 2024-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0010_billing_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='amount_btc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
