# Generated by Django 5.0.4 on 2024-05-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0016_billing_pinding_ammount_alter_billing_amount_btc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
