# Generated by Django 5.0.4 on 2024-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0017_alter_billing_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount_btc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pinding_ammount',
            field=models.FloatField(null=True),
        ),
    ]
