# Generated by Django 5.0.4 on 2024-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briansclub', '0018_alter_billing_amount_alter_billing_amount_btc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='tx_urls',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
